### ISSUE TITLE
Neue Rolle in RV Gremium mit Lesezugriff auf TN Liste aller Kurse (4h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#1]
Wir brauchen in den RV Gremien eine neue Rolle, die Lese-Zugang auf die TN-Liste alle Kurse hat.

Neue Rolle auf 

* Mitgliederorganisation::Gremium::Ausbildungmitglied

Berechtigung
- layer__and_below_read
- ability particpations_show, Anmeldungen_show (optional, wenn deutlicher Mehraufwand)

**Comment by codez** [comment]
Ich gehe davon aus, dass es sich um alle Kurse des entsprechenden Regionalvereins handelt.

**Comment by nchiapol** [comment]
Korrekt. Hier der detailiertere Wunsch:

Wir möchten einen neue Rolle "Ausbildungsmitglied". Diese sollte bei den Kursen des Regionalverbands die Tabs "Teilnehmende" und "Anmeldungen" lesen können. Sie sollte aber selbst nichts verändern können.

**Comment by RolandStuder** [comment]
Abgedeckt durch: https://github.com/hitobito/hitobito/issues/275
