### ISSUE TITLE
Kontakt-Liste für provisorische Anmeldungen (4h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#10]
Beim Tab "provisorische Anmeldungen" soll die Möglichkeit hinzugefügt werden, die Kontakt-Infos der provisorisch Angemeldeten als CSV herunterzuladen.

Adressliste Export für Tentatives siehe z. B. http://cevi.puzzle.ch/groups/1/events/1059/tentatives

**Comment by codez** [comment]
Participations CSV verwenden.

Schätzung: 0.5PT

**Comment by RolandStuder** [comment]
abgedeckt durch https://github.com/hitobito/hitobito/issues/277
