### ISSUE TITLE
Rechnungslayout hat Anschrift neu links

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#106]
Seit dem Release vom 2023-03-07 ist die Anschrift bei Rechnungen auf der linken Seite (vorher war sie rechts). Unsere Geschäftsstelle kann deshalb die bestehenden Kuverts mit Fenster nicht mehr benutzen.

Soweit ich weiss, haben wir keine solche Anpassung gewünscht. Entsprechend betrachte ich das als Bug. Oder gibt es eine Möglichkeit das einfach zu konfigurieren die wir übersehen haben? 

Da dies den Versand von Papier-Rechnungen deutlich aufwändiger macht, ist das relativ dringend für uns.

**Comment by ThomasEllenberger** [comment]
Vermute dass dies mit https://github.com/hitobito/hitobito_sww/issues/59 zusammenhängt, welches wir zwischen eurem letzten Release und heute umgesetzt haben. 

Ihr könnt die Rechnungsposition pro Layer auf den Gruppeneinstellungen ändern. Dies gilt jeweils für Briefe und Rechnungen:
![grafik](https://user-images.githubusercontent.com/100761305/223943641-cdf7af57-9e06-4b52-99cf-1d43b3d24e49.png)

**Comment by nchiapol** [comment]
Super, vielen Dank für die Antwort. Habe das eben für die Region Zürich umgestellt und das Funktioniert.

Dinge die mir aufgefallen sind/Probleme:
  * Bei der Region ist ein Logo definiert. Das erscheint aber nicht auf der Rechnung. (vgl. meinen Kommentar hier https://github.com/hitobito/hitobito/issues/921)
  * Die Einstellungen sind nicht nur pro Layer sonder pro Gruppe verfügbar. Mir ist nicht klar wann welche Einstellungen greifen. 

@ThomasEllenberger: Ich schliesse dieses Issue, da das ursprüngliche Problem erledigt ist. Allenfalls lohnt es sich aber die beiden neuen Punkte separat zu erfassen.
