### ISSUE TITLE
J+S Angaben auf Profil können nicht bearbeitet werden

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#107]
Die Infos zu AHV-Nummer, J+S Nummer und Nationalität gemäss J+S werden auf den Profilen zwar angezeigt:

![screenshot_2023-03-08_235354](https://user-images.githubusercontent.com/1123483/223869848-8e0f49d6-8113-4a2f-b2d6-28365835da64.png)

Aber fehlen im dazugehörigen Formular:

![screenshot_2023-03-08_235531](https://user-images.githubusercontent.com/1123483/223870056-e62df999-f434-4fae-ab29-1f5a30e0ebe9.png)

Da die für diese Infos für die Kurse wichtig sind, ist dieser Bug dringend.

**Comment by nchiapol** [comment]
Wurde da evtl. beim Ausblenden der Felder für den Elternzugang etwas viel erwischt?

**Comment by ThomasEllenberger** [comment]
Die Vermutung könnte korrekt sein.
Auf der PBS -Integration stosse ich auf das gleiche Problem @Michael-Schaer.

Wir schauen uns das an.

**Comment by Michael-Schaer** [comment]
@ThomasEllenberger : Bei uns ist es neu auch auf der Produktion der Fall (z.B. auch das AHV-Feld). Bitte mit Priorität fixen!

**Comment by ThomasEllenberger** [comment]
@nchiapol & @Michael-Schaer: wir konnten diesen Bug bereits beheben, benötigt jedoch einen erneuten Release. Kommt doch auf mich zu wann wir diesen für euch durchführen dürfen.
