### ISSUE TITLE
Neue Rolle "Helfer" bei Kursen (2h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#11]
Wir möchten bei Kursen eine neue Rolle "Helfer" mit den gleichen Rechten wie die Küche.

**Comment by RolandStuder** [comment]
Ok, da müssen wir noch etwas schauen. Die Rollen bei den Kursen sind über alle Organisationen gleich, soweit ich weiss. Und die aktuellen Rollen, entsprechen den J+S Rollen. Wir müssen schauen, dass wir damit keine Verwirrung erzeugen.

**Comment by nchiapol** [comment]
Bei uns sind mit "Küche", "Kassier" und "Referent" 3 von 5 Rollen keine definierten J+S Rollen. 
Das Anliegen ist aber nicht extrem wichtig, falls die anderen Nutzer gegen eine solche Rolle sind, können wir auch damit leben.

**Comment by RolandStuder** [comment]
Ok, hatte falsch gemeint. Können wir anpassen.

**Comment by codez** [comment]
Schätzung: 0.25PT

**Comment by RolandStuder** [comment]
Abgedeckt in https://github.com/hitobito/hitobito/issues/273
