### ISSUE TITLE
Bei Anlässen optional eine Unterschrift verlangen können (2h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#12]
Die Funktionalität aus den Kursen von 
  * Unterschrift erforderlich
  * Zweitunterschrift erforderlich
  * Zweitunterschrift von

Sollte auch für Anlässe verfügbar sein.

Ist aktuell nur auf Kursen verfübar: https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/models/event/course.rb

**Comment by codez** [comment]
Schätzung: 0.25PT

**Comment by RolandStuder** [comment]
abgedeckt durch https://github.com/hitobito/hitobito/issues/271
