### ISSUE TITLE
Neue Rolle "Sektionsadmin" (2h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#13]
Die Ebene "Sektion" braucht eine Rolle "Administrator/-in" mit ":layer_and_below_full" (sonst können auf dieser Ebene keine Anlässe oder Abos angelegt und Filter gespeichert werden.)

Weitere Berechtigungsanpassungen in #2 #6

**Comment by RolandStuder** [comment]
Ok. Eine neue Rolle mit Standberechtigungen ist mit wenig Aufwand machbar.

**Comment by codez** [comment]
Schätzung: 0.25PT

**Comment by RolandStuder** [comment]
adressiert in https://github.com/hitobito/hitobito/issues/270
