### ISSUE TITLE
Sicherheit: Aktualisierung Rollenberechtigungen

### ISSUE THREAD

**Issue by patrickuhlmann** [hitobito/hitobito_cevi#132]
Als Betreiber
möchte ich zwar eine gewisse Sichtbarkeit von Personen ermöglichen,
um den Austausch und eine effiziente Zusammenarbeit zu fördern.
Allerdings soll dies rollenabhängig erfolgen.

# Tech-Spec

Untenstehend wird jeweils die Notation Ebene/Gruppentyp/Rolle verwendet.

- Dachverband/Dachverband/Administrator -> 2FA Zwang einführen
- Dachverband/Geschäftsstelle/*Alle Rollen* -> 2FA Zwang einführen
- Dachverband/Gremium -> Ermöglichen darunter Gruppen vom Typ "Externe" zu erstellen. Falls dies aufwändig ist alternativ eine Rolle "Externe" ergänzen, welche keine Rechte besitzt

- Mitgliederorganisation/Mitgliederorganisation/Administrator -> 2FA Zwang einführen
- Mitgliederorganisation/Geschäftsstelle/*Alle Rollen* -> 2FA Zwang einführen
- Mitgliederorganisation/Gremium -> Ermöglichen darunter Gruppen vom Typ "Externe" zu erstellen. Falls dies aufwändig ist alternativ eine Rolle "Externe" ergänzen, welche keine Rechte besitzt

- Jungschar/Jungschar/(Aktuar|Freier Mitarbeiter|Lädeli|Redaktor|Regionaltreffvertreter|Webmaster|Materialverantwortliche|Kontakt Regionalzeitschrift) -> Die Berechtigung "Lesen Baum" entfernen
- Jungschar/Team/*Alle Rollen* -> Die Berechtigung "Lesen Gruppe" zuweisen
- Jungschar/Stufe/(Minigruppenleiter|Helfer) -> Die Berechtigung "Baum lesen" entfernen, dafür "Gruppe lesen" zuweisen

# Noch zu prüfen

- Soll auf Mitgliederorganisation/Gremium effektiv eine Rolle "Aktiver Kursleiter" und "Ausbildungsmitglied" existieren? Falls dies nur dazu dient eine gewisse Sichtbarkeit zu erhalten um Teilnehmer/Leiter zu suchen allenfalls umbenennen
- Soll auf Ortsgruppe/Ortsgruppe die Rolle Kassier entfernt werden?
- Können auf der Ebene Jungschar einige Rollen entfernt werden da diese nicht (mehr) relevant sind, z. B. Input?

# ToDo

**Comment by nchiapol** [comment]
Ich habe eben die verschiedenen Themen in vier einzelne Issues aufgeteilt: 
* #133 
* #134 
* #135 (die Liste der betroffenen Rollen in Jungschar/Jungschar ist grösser als hier, mir war nicht klar weshalb wir da nicht alle Rollen berücksichtigt hatten.)
* #136 

Ausserdem habe ich jeweils versucht ein Vorgehen zu Skizzieren und zu erwähnen, wo wir das selbst umsetzen können sollten.
