### ISSUE TITLE
neue API Endpunkte

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#14]
Wir möchten via API auch JSON-Antworten für die 
  * TN-Liste der Kurse: (groups/X/events/Y/participations) 
  * den Verlauf einer Person (groups/X/people/Y/history; oder via Query-String auf groups/X/people/Y auch alte Events und Rollen aktivieren lassen.)

**Comment by RolandStuder** [comment]
Abgelöst von #17 und #18
