### ISSUE TITLE
Fehlerhaftes Handling der Kontakt-Adresse bei Kursbestätigung

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#15]
Wir haben zwei Probleme bei der Kontaktadresse festgestellt:
  * Wenn die Kontaktperson bei Kursen eine Firma (bei uns den RV) eingetragen hat, so sollte die Adresse in der Bestätigung auch den Firmennamen enthalten. (Als z.B. Cevi Regionalverband ZH-SH-GL, Hans Mustermann v/o Musti, ....) Ohne Firmennamen ist ein Brief nicht zustellbar. **Wichtig, es geht um den Fall, wo eine Firma eingetragen ist aber die Checkbox "Firma" NICHT gesetzt ist.**
  * Wenn das Adressfeld mehrere Zeilen enthält, sollten die New-Line durch Komma ersetzt werden. (Postfach, Strasse), siehe auch auf untenstehendem Screenshot "Anmeldung an"

(Wir sehen dies als Bugs)

![image](https://cloud.githubusercontent.com/assets/194364/24887637/7d2bb556-1e5d-11e7-89ad-24d74570bb97.png)

**Comment by RolandStuder** [comment]
@nchiapol  Geht es hier um die gedruckte Anmeldung? Also diese Darstellung?

Wieso mehere Zeilen durch Komma ersetzen? Geht es darum, dass bei zu vielen Daten untenstehender Text überlagert wird? siehe Bug: https://github.com/hitobito/hitobito/issues/21

![image](https://cloud.githubusercontent.com/assets/194364/23617148/5bc5e93c-028c-11e7-8848-bc27eae0f217.png)

**Comment by RolandStuder** [comment]
@nchiapol Ah, ich glaube ich verstehe, jetzt es geht um die Kontaktadresse die am Ende der druckbaren Kursbestätigung angezeigt wird. Korrekt?

**Comment by nchiapol** [comment]
@RolandStuder genau. es geht um die Zeile zu unterst auf der Kursbestätigung "Anmeldung an"

**Comment by hupf** [comment]
Habe das Rendering der Kontaktperson entsprechend angepasst.
