### ISSUE TITLE
Kurse bleiben auf Profil-Seite von Abgemeldeten TN aufgeführt

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#16]
Zwei unserer Mitglieder haben sich letztes Jahr für einen Kurs an- und danach wieder abgemeldet. Der Kurs ist längst vorbei, wird aber auf ihrer Profil-Seite immer noch unter Anmeldung aufgeführt.

Betroffene Person z.B.: "Frisbii" aus STA. 

(Wir sehen das als Bug)

Canceled Participations sollten nicht auf der person show view erscheinen.

**Comment by RolandStuder** [comment]
Ja, das tönt nach einem Bug. Danke für den Hinweis.

**Comment by RolandStuder** [comment]
Fixed in next release
