### ISSUE TITLE
TN Liste von Kurs als JSON-API (8h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#17]
TN-Liste der Kurse: (groups/X/events/Y/participations) als JSON

gemäss Wunsch in #14

**Comment by codez** [comment]
Braucht es zwei Versionen analog CSV, welche je nach Berechtigung verfügbar sind?

**Comment by codez** [comment]
Schätzung: 1PT

**Comment by nchiapol** [comment]
analog Personen API passt.

**Comment by MrTinnysis** [comment]
Wir gehen davon aus, dass mit der Anpassung für alle Typen von Events (Anlässe und Kurse) die Teilnehmer ausgelesen werden können.

**Comment by amaierhofer** [comment]
@MrTinnysis @nchiapol  Die Änderungen sind auf integration gedeployed. Sind die enthaltenen Attribute für euch ausreichend? Soll dieses API auch für Service Tokens (API-Keys auf der Gruppe) erreichbar sein? Falls ja müssen wir noch festlegen wie / ob die Teilnehmerliste gefiltert werden soll?

**Comment by MrTinnysis** [comment]
Ich habe den Endpunkt kurz angetestet.
>Sind die enthaltenen Attribute für euch ausreichend?

Passt meiner Meinung nach so.
>Soll dieses API auch für Service Tokens (API-Keys auf der Gruppe) erreichbar sein? Falls ja müssen wir noch festlegen wie / ob die Teilnehmerliste gefiltert werden soll?

Ich bin der Ansicht, dass möglichst alle Endpunkte auch für die Service Tokens erreichbar sein sollten. Wir haben hierfür auch bereits eine Anwendung mit der NextCloud Gruppensynchronisation. Hier wäre wohl ein neues Recht sinnvoll: "Teilnehmende von Events dieser Ebene". Meiner Meinung nach sollte ein Service Token nur auf die Teilnehmenden von Events Zugriff haben auf der es eingerichtet wurde. Dafür würde ich das Filtering der Teilnehmerliste verzichten.

**Comment by amaierhofer** [comment]
@MrTinnysis Habe Teilnehmer in ServiceTokens mitaufgenommen und neu deployed.

**Comment by MrTinnysis** [comment]
@amaierhofer Auch hier macht in Meinen Augen die Variante Layer mehr Sinn alls die Variante Layer and below - also entweder beide Optionen anbieten oder nur die eingeschränkte Variante. Finde ich allerdings weniger kritisch als bei den Rechnungen.

**Comment by nchiapol** [comment]
* Ich unterstütze die einschränkung auf Layer - TN der Anlässe werden wohl nur von der entsprechenden Ebene bearbeitet.
* Im Moment ist das entsprechende Recht auch sprachlich noch falsch:
![image](https://user-images.githubusercontent.com/1123483/70854768-a809f380-1ec0-11ea-9025-5af2715fa4fd.png)
(Korrekt wäre wohl "Teilnehm**ende von Anlässen dieser** und ...")
* Der Enpunkt `https://cevi.puzzle.ch/groups/5/events/1104/participations/127608.json?token=<token>` sollte auch die Anmeldeangaben (die zusätzlichen Fragen) zur Anmeldung enthalten.
* Die URL `https://cevi.puzzle.ch/groups/5/events/1104/participations.csv?token=<token>` führt zu einem 500. ich hätte 403 erwartet
* Ausserdem (gehört nicht direkt zu diesem Issue): Der Titel der Seite mit den API-Keys ist "API-Keys" statt dem Gruppennamen (vgl. die folgenden Screenshots)
![image](https://user-images.githubusercontent.com/1123483/70855211-90823900-1ec7-11ea-889f-cbffd10875f1.png)
![image](https://user-images.githubusercontent.com/1123483/70855214-9d069180-1ec7-11ea-8b29-4d41550e9a3e.png)

**Comment by amaierhofer** [comment]
Wurde angepasst und auf integration deployed, bitte Ticket schliessen falls das jetzt für dich so stimmt @nchiapol @MrTinnysis

**Comment by nchiapol** [comment]
Eben kontrolliert, ist ok für mich. @MrTinnysis bitte schliessen wenn das auch für dich ok ist

**Comment by MrTinnysis** [comment]
Stimmt für uns so auch.
@amaierhofer Bitte beim Produktiven Release das Feature "Kursmarktplatz / Auswahl der Ausweichkurse" nicht aktivieren, das Feature ist grundsätzlich interessant wir brauchen allerdings für eine solche Erweiterung etwas Vorlaufzeit.
