### ISSUE TITLE
Coach Zugriffserweiterungen 2h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#2]
Die Rolle J+S Coach der Abteilungen braucht Zugriff auf die Anlässe (am
einfachsten wohl via :layer_and_below_full) sowie das Tab "Ausbildung"

**Comment by nchiapol** [comment]
Wir haben das noch einmal genauer angeschaut und hier sollte wirklich einfach die Berechtigung :layer_and_below_read durch layer_and_below_full ersetzt werden

**Comment by RolandStuder** [comment]
adressiert in https://github.com/hitobito/hitobito/issues/270
