### ISSUE TITLE
Log zeigt nicht mehr an, wer eine Änderung gemacht hat

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#21]
Seit dem letzten Update ist im Log nicht mehr ersichtlich, wer etwas geändert hat (auch für mich als Admin). Das reduziert den Nutzen des Logs beträchtlich. Dazu steht auch nichts im Changelog und die Änderung ist bei uns definitiv unerwünscht. Entsprechend betrachten wir das als Bug. Könnt ihr das anschauen und korrigieren?

**Comment by RolandStuder** [comment]
Danke für den Hinweis. Das ist klar ein Bug und er tritt bei allen Kunden auf.

**Comment by RolandStuder** [comment]
Gefixt, wird aber erst mit dem nächsten Release ausgerollt.

**Comment by nchiapol** [comment]
Sehr schön. Ist nach dem Release auch bei alten Änderungen ersichtlich wer dafür verantwortlich war? Oder nur bei Änderungen die nach dem Release gemacht werden? (Wird der Ändernde im Moment erfasst aber nicht angezeigt oder wird er gar nicht erfasst?)

Falls der Fix auch Rückwirkend funktioniert, eilt das aus meiner Sicht überhaupt nicht. Sonst wäre ein baldiges Release schon schön.

**Comment by nchiapol** [comment]
funktioniert unterdessen wieder, leider nicht Rückwirkend
