### ISSUE TITLE
CSV-Import: Name != Ceviname

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#24]
Beim CSV-Import wird die Spalte "Name" standardmässig mit Ceviname verknüpft. Nachname wäre sinnvoller.

see https://github.com/smathys/hitobito_cevi/issues/27

**Comment by RolandStuder** [comment]
Ok. 

Bräuchte eine Anpassung vom https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/domain/import/person_column_guesser.rb

Am besten wohl wohl eine neues Mapping machen, dass auch weitere Vorschläge enthält. Z. B. Mobile -> phone_number_mobil und ähnliches.

**Comment by nchiapol** [comment]
kann geschlossen werden
