### ISSUE TITLE
Trennzeichen zwischen zwei Gruppen (">") nicht konsistent 

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#25]
Das Trennzeichen zwischen zwei Gruppen ist nicht konsistent.

Suche: (parent > child)
Breadcrumb oben rechts: (child > parent)

![image](https://user-images.githubusercontent.com/631965/37728249-0d7ec3b4-2d3a-11e8-858a-d3b2ce26a586.png)

see https://github.com/smathys/hitobito_cevi/issues/28

**Comment by RolandStuder** [comment]
In der Tat. Danke für den Hinweis.

**Comment by nchiapol** [comment]
checked - besteht noch

**Comment by carlobeltrame** [comment]
Wie hättet ihr das denn gerne? Und wo ist die Suche die ihr konkret meint? Ich habe es gefunden beim Hinzufügen von Abonnenten zu einem Abo, gibt es das sonst noch irgendwo?

**Comment by maede97** [comment]
Zur Suche:
Wenn man im normalen Suchfeld z.b. nach einer Abteilung sucht (z.B. "Bäretswil") werden dann die Untergruppen angezeigt der "JS Bäretswil"und zwar im Format "JS Bäretswil > Externe". (siehe erster Kommentar: suche hat parent > child). 

Im Breadcrumb oben rechts: (child > parent)

**Comment by nchiapol** [comment]
Persönlich würde ich wohl einfach bei der Suche die Reihenfolge drehe, so dass sie Analog zum Breadcrumb ist.

**Comment by nchiapol** [comment]
Per 2024-01-09 wird das Trennzeichen bei der Suche durch eine  → ersetzt, damit ist das erledigt.
