### ISSUE TITLE
 Hinzufügen alternative Email Adresse standardmässig „Versand“ nicht aktivieren

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#26]
Wenn eine alternative Email Adresse hinzugefügt wird, hätten wir gerne, dass die Checkbox für „Versand“ standardmässig nicht deaktiviert wird.

Durch automatische aktivieren der Checkbox, kann diese Information übersehen werden und ist somit fehleranfällig

see https://github.com/smathys/hitobito_cevi/issues/16

**Comment by RolandStuder** [comment]
Macht sicher mehr Sinn, ich habe das veranlasst, siehe obenstehenden Pull-Request.
