### ISSUE TITLE
 Rollen im People-Export nicht identisch mit Subscription-Export

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#27]
Rollen im People-Export sind nicht identisch mit Subscription-Export. Der People-Export ist korrekt, der Subscription Export enthält zum Teil alte Rollen.

see https://github.com/smathys/hitobito_cevi/issues/40

**Comment by RolandStuder** [comment]
Kannst du beurteilen, ob das vielleicht dasselbe Problem ist, wie dieses: https://github.com/hitobito/hitobito/issues/423 

Dann wäre es mit dem neuen Release dann bereits gefixed.

**Comment by RolandStuder** [comment]
@smathys Kannst du beurteilen, ob das vielleicht dasselbe Problem ist, wie das untenstehende? : hitobito/hitobito#423

Dann wäre es mit dem neuen Release dann bereits gefixed.

**Comment by nchiapol** [comment]
hitobito/hitobito#423 
Scheint unserem Problem zu entsprechen. Die Rollenbezeichnungen scheint korrekt, die Gruppe ist definitiv falsch.

**Comment by smathys** [comment]
@nchiapol Wir konnten diesen Fehler bei uns im Testsystem nicht nachvollziehen oder?
Deshalb könnte es im neuen Release wirklich schon gefixed sein.

**Comment by RolandStuder** [comment]
Ich schliesse diesen Bug, bitte hier kommentieren, falls ihr doch noch etwas findet.

**Comment by RolandStuder** [comment]
Wahrscheinlich ist der eben schon gefixed, er wurde damals von der PBS gemeldet und gefixed.

**Comment by smathys** [comment]
@RolandStuder wir haben noch ein anderes "Problem". Wieso wurden beim Abo Export die anderen Detail Felder entfernt? Wir haben Leute, die diese Export weiter verarbeitet haben und mit dem kommenden Release nun die benötigten Informationen nicht bekommen. Es wäre zumindest gut, wenn wir jeweils vor den Releases erfahren, wenn etwas "vereinfacht" wurde

**Comment by RolandStuder** [comment]
@smathys Bitte jeweils für anderes neue Issues eröffnen. Zum anderen habe ich dir ja ein e-Mail geschrieben: Die Detailfelder wurden nicht entfernt, aber wir hatten auf "Haushaltsexport" umgeschaltet, dank https://github.com/hitobito/hitobito/issues/483 hat man aber wieder die Wahl.

**Comment by nchiapol** [comment]
Wir konnten das bisher im Testsystem nicht kontrollieren, da dort der entsprechende Export gefehlt hat. Mit https://github.com/hitobito/hitobito/issues/483 ist das nun aber ja wieder möglich. Ich sehe das Problem auch nicht mehr im Testsystem.
