### ISSUE TITLE
nicht druckbare Zeichen bei Texteingabe und Import ignorieren

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#28]
Durch copy & paste bei editieren sowie bei Inputfiles für den Import wäre es schön, wenn nicht druckbarezeichen wie 

- whitespace

- newlines
automatisch ignoriert/gefiltert/getrimmt werden

see https://github.com/smathys/hitobito_cevi/issues/10

**Comment by RolandStuder** [comment]
@smathys Kannst du hier noch konkreter werden. Beim Import wird bereits Whitespace am Anfang und Ende der Einträge entfernt. Newlines muss man genauer anschauen, weil die bei Feldern wie Adresse und weitere Angaben manchmal durchaus erwünscht sind.

Wo seid ihr darauf gestossen, dass hitobito nicht sinnvoll mit den Importdaten umgeht?

**Comment by nchiapol** [comment]
Habe das eben noch einmal angeschaut und kann das mit Space und Newline nicht reproduzieren. Ich vermute das war ein alter Bug, von dem wir nie mitgekriegt haben, dass er gefixt ist - und den wir nicht sauber überprüft haben.
(Aus meiner Sicht muss nur Whitespace und Co am Anfang und Ende gefiltert werden.)

**Comment by smathys** [comment]
wir closen den Issue, da wir das Problem wohl auf einer alten Version entdeckt hatten
