### ISSUE TITLE
Provisorische Anmeldung

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#29]
Wir haben das Problem gefunden:

Die Person ist nur provisorisch bei dem Kurs angemeldet. Die Rolle wurde bei jedem Versuch korrekt vergeben: https://db.cevi.ch/groups/3/events/279/participations/12393

Da die Anmeldung nur provisorisch ist, taucht sie in der Liste der definitiven Teilnehmer nicht auf. Und dies eben auch, wenn sie weitere Rollen hat.

Da die Anmeldung ja darauf zielt, Teilnehmer zu sein, ist es vermutlich nicht sinnvoll, bei einer unterstützenden Rolle diese Anmeldung zu bestätigen. Allenfalls könnte es noch sinnvoll sein, die Anmeldung abzulehnen, da die Person durch die unterstützende Tätigkeit eben nicht mehr Teilnehmer ist. Oder eben nur die Person anzuzeigen und so zumindest mehrfache Rollenvergabe zu verhindern. In diesem Fall sollten aber die provisorischen Rollen nicht in der Liste auftreten.

Grundsätzlich sehe ich einen Konflikt zwischen den Rollen Teilnehmer und Küche (in diesem Fall), es betrifft aber vermutlich noch anderen Rollenpaare (wie Leitung und Teilnehmer).

Was ist hier inhaltlich die richtige Änderung?

Eine Warnung, dass die Person bereits provisorisch angemeldet ist?
Eine automatische Bestätigen der provisorischen Anmeldung?
Eine automatisches Löschen der provisorischen Anmeldung?
Die Person trotzdem in der Teilnehmerliste anzeigen, unabhängig von anderen Anmeldungen?
Ist jetzt vielleicht ein bisschen technisch aber wir müssen da eine der obenstehenden inhaltliche Anpassung vornehmen. Was würdet ihr erwarten, wenn ihr eine Person die provisorisch angemeldet ist als Helfer aufnehmt, was sollte dann passieren? Die provisorische Anmeldung löschen?

see https://github.com/smathys/hitobito_cevi/issues/41

**Comment by smathys** [comment]
Hallo Roland

Danke für die schnelle Klärung.
Ich hatte die Ursache in dieser Richtung vermutet, habe es jedoch nicht geschafft dies zu verifizieren.

Wir erfassen potentielle Kursmitarbeiter auch als potentielle Teilnehmer. Daher erscheint mir eine automatisches Bestätigung der provisorischen Anmeldung die richtige Lösung.

Gruss Markus

**Comment by smathys** [comment]
Hallo Roland

Aufgrund von Rückmeldungen aus unserem Team eine Präzisierung.
Wird einer Person (welche provisorisch angemeldet ist) eine Teamrolle vergeben, wir die provisorische Anmeldung insofern bestätigt, dass die Person nicht mehr als provisorische Teilnehmerin gilt.
Für den konkreten Fall bedeutet dies wohl nicht Bestätigung der provisorischen Anmeldung sondern Löschung...

Gruss Markus

**Comment by smathys** [comment]
Hallo Roland

Leider habe ich nichts mehr gehört.
Anfang Jahr bestand das Problem gemäss unserem Sekretariat nach wie vor.
Wie ist der Stand und das Vorgehen?

Gruss Markus

**Comment by RolandStuder** [comment]
@smathys Der ist eigentlich gefixed, siehe https://github.com/hitobito/hitobito/issues/395, aber wir haben bei euch wider erwarten noch keine neuen Release gemacht. Mit dem neuen Release wird das gefixed, allerdings nur für neue Zuweisungen. Aber wenn man eine Person dann nochmals hinzugefügt, wird die provisorische Anmeldung dann jeweils gelöscht.

**Comment by nchiapol** [comment]
kann geschlossen werden
