### ISSUE TITLE
TN Liste sortierbar nach Ortsgruppe 4h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#3]
* Auf TN-Listen von Kursen wird bereits die Ortsgruppe angezeigt (Wagon, ist ein Attribut) .
* Die TN-Liste von Kursen/Anlässen sollte nach Ortsgruppe sortiert werden können
* Ortsgruppe ist ein Personenattribut und nicht zwingen identisch mit der Hauptebene (siehe https://github.com/hitobito/hitobito_cevi/blob/master/app/models/cevi/person.rb#L70)
* Im Export bereits vorhanden

Daher passt folgendes Issue nicht: Beachte: https://github.com/hitobito/hitobito_pbs/issues/50 (ohne explizite Erwähnung von Sortierung)

**Comment by nchiapol** [comment]
* Soweit ich das gesehen habe, wird die Ortsgruppe bei allen Team-Mitgliedern, nicht aber bei den TN angezeigt.
  * Die Ortsgruppe ist bei uns ein Personen Attribut und nicht zwingend identisch mit der Hauptebene.

**Comment by RolandStuder** [comment]
Schliesse dieses Issue zugunsten von: https://github.com/hitobito/hitobito/issues/269
