### ISSUE TITLE
Etiketten mit langen Adressen wegen Haushalten

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#30]
sobald 4 Personen im Haushalt sind und eine Ettikette via eigener Ettikennten-Vorlage erstellt wird, 
wird die Ortschaft abgeschnitten, da der Text zu lange wird.
siehe
https://user-images.githubusercontent.com/14098502/41110152-00bf307e-6a79-11e8-8152-43063b944a19.png

Unser Wunsch wäre, dass hier generell eine kleinere Schriftart verwendet wird, wenn Ettikenten mit Haushalten für eigene Ettiketten-Vorlagen generiert werden.

see https://github.com/smathys/hitobito_cevi/issues/48

**Comment by KunoKunz** [comment]
Ich denke, dass ihr bei den Einstellungen im Etikettenformat die Schriftgrösse selber definieren könnt.

**Comment by maede97** [comment]
Ja, man kann ja eine eigene Schriftgrösse erstellen. Falls ich nun aber eine möglichst grosse Schrift für die Etiketten haben möchte, werde ich nicht durchprobieren, bis alle Etiketten stimmen. Da wäre es sicher wünschenswert, wenn da die DB automatisch erkennt, dass zuviel Text auf einer spezifischen Etikette ist und nur diesen Text kleiner macht, damit alle anderen doch noch gross bleiben.
