### ISSUE TITLE
Export "Excel Haushaltsliste" auf Anlässen fasst Haushalte nicht zusammen

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#31]
Der Excel Export eines Anlass als Haushaltliste funktioniert nicht korrekt, es wird die vollstaendige Liste versandt.
Beispiel aus der Testumgebung

[event_participations_export (2).xlsx](https://github.com/hitobito/hitobito_cevi/files/2112522/event_participations_export.2.xlsx)

see https://github.com/smathys/hitobito_cevi/issues/51
see https://github.com/hitobito/hitobito/issues/494

**Comment by MrTinnysis** [comment]
kann geschlossen werden
