### ISSUE TITLE
Testsystem Hintergrundfarbe ändern

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#32]
Ist es möglich auf dem Testsystem der Cevi die Hintergrundfarbe zu ändern, damit wir Test und Produktiv System besser auseinander halten können?

Ceviblau: #0026ff oder ähnliches

see https://github.com/smathys/hitobito_cevi/issues/52

**Comment by nchiapol** [comment]
hack: Neu kann das Logo geändert werden (wird aber nicht überall übernommen). Für die Integrationsumgebung ist das Logo jetzt auf "INTEGRATION" gesetzt.

**Comment by nchiapol** [comment]
abgeschrieben
