### ISSUE TITLE
Geändert und Log stimmen nicht überein

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#33]
Wir haben schon 2 Fälle wo die Log-Einträge nicht mit *geändert* auf der Ansicht Info einer Person übereinstimmen

Bei mindestens einem Kontakt (Rajona, HOM) steht aktuell

Erstellt
24.09.2014 15:14 [...] Cleo (Geschäftsstelle)
Geändert
23.03.2018 08:13 Nicolas [...]
der letzte Log Eintrag ist:

Dienstag, 13. März 2018, 15:22 Uhr 
von [...] / Sima

Gleiches geht auch andersum (das heisst, Log ist älter):
Ich habe mir soeben eine neue Rolle in JS Bäretswil gegeben.
Geändert 04.06.2018 13:50 Matthias Busenhart / Scirocco
und im Log:
Dienstag, 19. Juni 2018, 18:44 Uhr von Matthias Busenhart / Scirocco Rolle Materialverantwortliche/-r (Vermietung) in JS Bäretswil wurde hinzugefügt.

see https://github.com/smathys/hitobito_cevi/issues/43

**Comment by RolandStuder** [comment]
Rollenänderungen, Vergaben von Tags sind nicht direkt attribute der Person. Das "geändert am" Datum zeigt auf wann Personenattribute geändert wurden.

Natürlich wäre es trotzdem möglich, dass wir das Datum entsprechend immer aktualisieren würden, wenn eben Rollen oder Tags verändert werden. Gehört dann eine Qualifikation hinzufügen auch dazu? Eine Event Anmeldung aber wohl nicht.

**Comment by nchiapol** [comment]
das ist so ok für uns. Dieses Jusse kann geschlossen werden.
