### ISSUE TITLE
CSV aus Export kann nicht direkt importiert werden

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#35]
Ein csv Export kann nicht direkt wieder importiert werden:

Werte "unknown" in Konfession und Anrede verursachen die Fehlermeldung: "Konfession ist kein gültiger Wert, Anrede ist kein gültiger Wert "

see https://github.com/smathys/hitobito_cevi/issues/42

**Comment by nchiapol** [comment]
kann geschlossen werden.
