### ISSUE TITLE
Haushalte Ettiketten nicht vollständig

### ISSUE THREAD

**Issue by smathys** [hitobito/hitobito_cevi#37]
Bei Anlässen (aufgefallen bei einem Anlass mit 70+ Personen) sind die Etiketten nicht immer komplett. Manchmal fehlen einige Adressen komplett, manchmal fehlen Personen auf einem Haushaltsetikett.
Ich habe auf die schnelle kein Muster erkennen können.

Details zum Fall:

https://db.cevi.ch/groups/1812/events/889/
Zweckform No.L7160 / J8160 (66.0mmx38.1mm) (Globales Etikettenformat)

see https://github.com/smathys/hitobito_cevi/issues/50

**Comment by MrTinnysis** [comment]
kann geschlossen werden
