### ISSUE TITLE
TN Liste soll Geburtsdatum enthalten 4h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#4]
* Neue Spalte für Geburtsdatum
* Sortierbar nach Geburtsdatum (jüngste/alteste)
* Nur für Teilnehmerlisten notwendig.

Use case ist Ich will zu junge  / zu alte Teilnehmer finden. Daher würde auch Jahrgang genügen, falls man das somit in den Core nehmen könnte.

Falls alle die Show_participation Zugriff haben, eh schon das Geburtsdatum sehen, dann bitte im Core umsetzen.

Todo

* [ ] Abklären, ob Geburtstsdatum irgendewie spezielle geschützt ist.
* [ ] Falls ja, dann mit Jubla / PBS und so klären

**Comment by nchiapol** [comment]
Für uns ist auch wichtig, dass nach dieser Spalte sortiert werden kann.

**Comment by RolandStuder** [comment]
@nchiapol Wie wäre die Sortierung? Nur nach Datum, so dass die Geburtstage übers Jahr hinweg  verteilt sieht, also 1.1.1980 vor 2.1.1970 oder wirklich nach Alter?

**Comment by RolandStuder** [comment]
@nchiapol Geht es nur um die Teilnehmerlisten bei Events/Kursen oder soll das auf der allgemeinen Personenliste auch angezeigt werden?

**Comment by nchiapol** [comment]
@RolandStuder 
  * Sortierung: Gute Frage! Für unseren primären UseCase (rasch sehen wer zu alt/zu jung für einen Anlass ist) brauchen wir Sortierung nach Alter.
  * Es geht nur um die TN-Listen bei Anlässen. (für die Personenliste wäre das sicher auch schön, aber dort können wir gut auf #5 warten.)

**Comment by RolandStuder** [comment]
abgedeckt durch https://github.com/hitobito/hitobito/issues/272
