### ISSUE TITLE
Produktionsrelease CEVI

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cevi#42]
Bitte beim Produktiven Release das Feature "Kursmarktplatz / Auswahl der Ausweichkurse" nicht aktivieren, das Feature ist grundsätzlich interessant wir brauchen allerdings für eine solche Erweiterung etwas Vorlaufzeit.

Ev. noch im Zusammenhang: https://github.com/hitobito/hitobito_cevi/issues/41

**Comment by olibrian** [comment]
@amaierhofer könntest du bitte den Release in der KW2 machen?

**Comment by amaierhofer** [comment]
@olibrian ja das sollte klappen, allerdings verstehe nicht was mit 

> Feature "Kursmarktplatz / Auswahl der Ausweichkurse" 

gemeint ist. Hast du da noch mehr Informationen dazu?
