### ISSUE TITLE
Spender-Schutz kann via Filter zum Teil umgangen werden

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#44]
Wenn ich auf eine Spender Gruppe einen Filter nach der Rolle Spender anwende, ist die Resultat Menge nicht leer (es sind nur wenige Personen sichtbar, aber eigentlich sollten keine Personen sichtbar werden). 

Auch ein Filter auf einer übergeordneten Ebene macht einzlene Personen mit Spender-Rollen sichtbar. Zudem wird die Spender-Rolle bei den Rollen in der Resultat-Liste des Filters angezeigt, selbst wenn ich nach einer anderen Rolle gesucht habe. (eine noch schwächere Version von https://github.com/cevi/hitobito_cevi/issues/12)

Beides scheinen kleinere Bugs.

**Comment by kronn** [comment]
@nchiapol Leider kann ich den Fehler noch nicht nachvollziehen. Gibt es hierfür ein konkretes Beispiel, idealerweise auf der Integrationsumgebung?

**Comment by nchiapol** [comment]
In der Integration konnte ich das Problem noch nicht nachstellen. In der Produktiv-Version kann ich es genauer beschreiben:
  * https://db.cevi.ch/groups/2320/people zeigt für mich korrekt drei Personen mit der Rolle "Spendenverwalter". https://db.cevi.ch/groups/2320/people?filters%5Brole%5D%5Brole_type_ids%5D=33-34&name=Gesamte+Gruppe&range=deep und
https://db.cevi.ch/groups/2320/people?filters%5Brole%5D%5Bfinish_at%5D=&filters%5Brole%5D%5Brole_type_ids%5D=33&filters%5Brole%5D%5Bstart_at%5D=&name=&range=deep
zeigen aber beide mehr Mitglieder, obwohl ich nur Spendenverwalter sehen dürfte.
  * Auch https://db.cevi.ch/groups/2/people?filters%5Brole%5D%5Bfinish_at%5D=&filters%5Brole%5D%5Brole_type_ids%5D=33&filters%5Brole%5D%5Bstart_at%5D=&name=&range=deep gibt ein nicht-leeres Resultat.
  * Die Suche https://db.cevi.ch/groups/2/people?filters%5Brole%5D%5Bfinish_at%5D=&filters%5Brole%5D%5Brole_type_ids%5D=24&filters%5Brole%5D%5Bstart_at%5D=&name=&range=deep listet im Moment alle Rollen der gefundenen Personen. Dabei zeigt sie für mich zum Beispiel bei Simon Boller auch Spender Rollen (die aber auf seiner Personen-Seite für mich nicht sichtbar sind)

**Comment by kronn** [comment]
Danke, das hat sehr geholfen. Ich konnte den Ort finden, an dem zuviel gefunden wurde und es wieder einschränken. Es wurden auch die Personen gefunden, die ihre Kontaktdaten öffentlich geschaltet haben. In meinem Test habe ich es jetzt so gemacht, dass dies nicht mehr berücksichtigt wird, aber man sich selbst finden kann. Ansonsten findet man aber nur, wen man auch normal sehen kann. Die Suche nach Spendern ist jetzt nur noch für Spendenverwalter sinnvoll.
