### ISSUE TITLE
TN Listen Spalten konfigurierbar machen 24h

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#5]
Statt fixe Tabelleneinträge auswählbar machen, was auf der Liste angezeigt werden soll.

* Einstellung pro Benutzer speichern (aber nicht pro Tabelle)

Siehe:
http://filamentgroup.github.io/tablesaw/demo/toggle.html

![image](https://cloud.githubusercontent.com/assets/194364/23156088/d047d2e2-f815-11e6-8767-84f401537edc.png)

Grobschätzung

**Comment by nchiapol** [comment]
Das sieht sehr interessant aus, passt aber nicht in den aktuellen Sprint. 

Trotzdem wären wir aber auf jeden Fall an einer solchen Funktionalität interessiert. Weitere Gednaken:
  * Auch das Personen-Tab von Gruppen sollte so konfiguriert werden können.
  * Idealerweise lässt sich diese Spalten-Auswahl auch als CSV exportieren.

**Comment by RolandStuder** [comment]
Schätzung 2-3PT (+1-2PT falls weitere, komplexere
Spalten wie z.B. Antworten dazu kommen)

**Comment by MrTinnysis** [comment]
mittlerweile möglich - kann geschlossen werden
