### ISSUE TITLE
Anlässe mit An- und Abmeldung

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_cevi#53]
see: https://github.com/cevi/hitobito_cevi/issues/67

**Comment by kronn** [comment]
Ist IMHO schon vorhanden, siehe https://github.com/cevi/hitobito_cevi/issues/67#issuecomment-742490641

**Comment by nchiapol** [comment]
Nein, das reicht nicht. Sorry, wenn das aus unserem Issue nicht klar wurde. Die Minimal-Anforderung ist, dass man sich bei einem Anlass direkt abmelden kann ohne vorher je angemeldet gewesen zu sein. 
Es geht um Anläss mit einem definierten Kreis möglicher Teilnehmer von denen wir auf jeden Fall eine Antwort möchten. (also entweder eine An- oder Abmeldung) so wissen wir, bei wem wir noch nachfragen müssen.

**Comment by chrusu** [comment]
Liste mit eingeladenen TN hinterlegen:
Das Hinzufügen via ist via Personen-Suche sinnvoll möglich. Wir möchten allerdings in diesem Fall eine aktive Bestätigung der Teilnehmer. d.h. wir bräuchten drei Stati: eingeladen, angemeldet und abgemeldet. Im Moment fehlt da der Zustand "Eingeladen"

**Comment by chrusu** [comment]
Guten Morgen @nchiapol: was hälst du von folgendem Umsetzungsvorschlag?

![anmeldungen](https://user-images.githubusercontent.com/17568539/112271192-e8871e00-8c7a-11eb-9e1a-f7c1e309ed3c.png)

wird um eine zusätzliche Spalte "Eingeladen" ergänzt, alsso ungefähr so:

![Anlässe mit An-_Abmeldung copy](https://user-images.githubusercontent.com/17568539/112271239-fa68c100-8c7a-11eb-9c17-841d3c111506.png)

und:

![2021-03-24_08-18](https://user-images.githubusercontent.com/17568539/112271256-ff2d7500-8c7a-11eb-98f6-4518d907359a.png)

wird ergänzt mit der Möglichkeit, die verschiedenen Stati (Angemeldet, Abgemeldet, Eingeladen) auszuwählen, wenn ein Teilnehmer manuell hinzugefügt wird.

![Anlässe mit An-_Abmeldung copy (Alternate 766k)](https://user-images.githubusercontent.com/17568539/112271497-4a478800-8c7b-11eb-9ff2-063fae92426d.png)

Was soll hier der default sein? Angemeldet oder Eingeladen?

**Comment by nchiapol** [comment]
Sorry für die lange Reaktionszeit. Der Kommentar ging bei mir in allen anderne Github-Notifications unter...

Problem mit dem Vorschlag scheint mir, dass das "Anmeldungen"-Tab im Moment nur bei Kursen besteht - und wir werden das wohl primär für Anlässe verwenden. (Und nur via Anlässe steht diese Option dann auch den Ortsgruppen zur Verfügung.)

Da wir bei diesem Feature primär an Anlässe denken, sollte zudem keine "Warteliste" implementiert werden. (Die scheint mir auch verwirrend.) Das heisst wir brauchen wirklich nur drei Stati:
  * eingeladen
  * angemeldet
  * abgemeldet

Auch Drag-n-Drop zwischen den Stati scheint mir nicht wichtig. Der Wechsel zwischen den Stati wird ja durch die eingeladenen TN selbst ausgelöst. Wenn sie den Event öffenen sollten sie eine entsprechende Nachricht sehen und Rückmeldung geben können:
![image](https://user-images.githubusercontent.com/1123483/113453961-67acec80-9407-11eb-96ea-c97ba1cf2831.png)


Grundsätzlich sehe ich zwei Optionen:
  1. ein neues Tab analog zu an Anmeldungen bei den Kursen mit der Liste der eingeladenen Personen sowie deren Antwort
![einladungen_mock](https://user-images.githubusercontent.com/1123483/113452926-51059600-9405-11eb-9c5e-35fe285ec539.png)
  1. zwei zusätzlicher "Filter"-Listen  bei den "Teilnehmenden" Analog zur "Abwesende"-Liste bei den Kursen  
![image](https://user-images.githubusercontent.com/1123483/113451238-e141dc00-9401-11eb-9892-4ddac0366add.png)

Wobei das Tab oder die zusätzlichen Listen allenfalls via Konfiguartion auf dem Anlass ("[ ] Anlass mit Einladungsliste") gesteuert werden könnten.

Persönlich scheint mir die zweite Variante eleganter.
Der dazugehörende Dialog könnte dann etwa so aussehen:
![image](https://user-images.githubusercontent.com/1123483/113451516-69c07c80-9402-11eb-8a97-8af216b05222.png)
Der Status "Einladung" könnte evtl. auch als eine Art "Pseudorolle" implementiert werden. Dabei wäre aber zu beachten, dass beim Hinzufügen der Rolle keine Anmeldefragen nötig sind. Beim richtigen Anmelden dann aber schon 

Unabhängig der Variante ist wichtig, dass die Rolle/dieser Status auch über den Masseneditierdialog "+Zu Veranstaltung hinzufügen" Im Personen-Tab der Gruppen vergeben werden kann.

**Comment by chrusu** [comment]
![Anlässe mit Einladung Variante B](https://user-images.githubusercontent.com/17568539/116865187-71de2880-ac09-11eb-91bd-de5a28f31382.png)
![Anlässe mit Einladung Variante A](https://user-images.githubusercontent.com/17568539/116865188-7276bf00-ac09-11eb-8045-8dfa6f26b79f.png)

@nchiapol Kurze Frage zum hinzufügen von mehreren Personen. Das 2te Bild basiert auf deinem Vorschlag wenn eine Person hinzugefügt wird.
Meinem Verständnis nach sollte das "eingeladen"-Attribut nicht die Rolle ersetzen, sondern ergänzen. Entsprechend mein Vorschlag, dieses Attribut loszulösen. Was denkst du dazu?

**Comment by nchiapol** [comment]
Ich glaube in 99% der Fällen werden wir nur die gewöhnlichen Teilnehmer einladen. Ein losgelöstes Attribut, bei dem dann für jede Rolle eingeladen werden könnte, wäre aber sicher flexibler. Falls das Aufwand-mässig keinen grossen Unterschied macht, dürft ihr das gerne so lösen.

**Comment by nchiapol** [comment]
Noch ein UI-Gedanke: In der Version mit dem losgelösten Attribut fände ich eine Radio-Auswahl [anmelden, einladen] mit anmelden als default wohl intuitiver als eine einzelne Checkbox einladen.

**Comment by chrusu** [comment]
merci für deine raschen feedbacks, ich habe noch einen weiteren vorschlag hochgeladen.

**Comment by chrusu** [comment]
duplicate: https://github.com/hitobito/hitobito/issues/1276
