### ISSUE TITLE
API: API Service Tokens haben keinen Zugriff auf die Spender

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_cevi#58]
see: cevi/hitobito_cevi#98

Durch eine der beiden Änderungen #12, hitobito#39 wurde auch der Zugriff der API Service Tokens auf die Spender gekillt. Ich denke dies ist nicht ausschliesslich schlecht, sollte aber mit einem zusätzlichen Recht bei Bedarf aktiviert werden können. Da beispielsweise das Finanztool der Region Bern vorzugsweise mit einem Service Token laufen würde. Habe dies temporär im Finanztool umgestellt und vorerst noch nicht weitergeleitet.

Ich wäre für eine neue Berechtigung:
Spender dieser Ebene
ohne Zugriff auf Spender darunterliegender Ebenen.

Anpassen zusammen mit den generellen Berechtigungen der API Tokens: #76

Entweder als neue Berechtigung für Tokens oder generelle Freischaltung für alle Tokens.

# Mockup

# Techspec

**Comment by MrTinnysis** [comment]
Ich habe noch einen Bug im Bereich Spenderrolle - API Service Token gefunden und dokumentiert: https://github.com/hitobito/hitobito_cevi/issues/78

**Comment by nchiapol** [comment]
erledigt unter https://github.com/hitobito/hitobito_cevi/issues/90
