### ISSUE TITLE
MIO-Admin kann "fremde" Kontakte löschen

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#59]
Beim Integrieren einer neuen MIO haben wir festgestellt, dass ein MIO-Admin selbst dann Kontakte löschen kann, wenn diese noch in einer anderen MIO verknüpft sind. Das sollte nicht möglich sein.
Lösungsoptionen:
  1. Das Löschen-Recht auf Admin des Dachverbands beschränken.
  2. Löschen nur für Kontakte Zulassen, bei denen der User für alle Rollen-Schreibrechte hat.

Bitte im Rahmen unseres Sprints fixen (mit der günstigeren Variante.)
(2. wäre wohl sauberer, 1. wohl einfacher)

**Comment by chrusu** [comment]
Lösungsvorschlag Variante 1:
MIO-Admin Permission "admin" entfernen.
