### ISSUE TITLE
Umstellung der Berechtigung von mehreren Rollen von :layer_and_below_full auf :layer_full (2h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#6]
Umstellung von einigen Berechtigungen

Betrifft konkret folgende Anpassungen:
 
**Auf Layer Dacherband** (nicht auf Mitgliederorganisationen)
  * Vorstand [layer_and_below_read -> layer_read]
    * Präsidium
    * Finanzverantwortliche/-r
    * Mitglied
  * Geschäftsstelle [layer_and_below_full -> layer_full]
    * Geschäftsleiter/-in
    * Angestellte/-r
    * Finanzverantwortliche/-r
  * Gremium [layer_and_below_read -> layer_read]
    * Leitung 
    * Mitglied
    * Aktive/-r Kursleiter/-in

**Comment by nchiapol** [comment]
Betrifft konkret folgende Anpassungen:

  * Vorstand [layer_and_below_read -> layer_read]
    * Präsidium
    * Finanzverantwortliche/-r
    * Mitglied
  * Geschäftsstelle [layer_and_below_full -> layer_full]
    * Geschäftsleiter/-in
    * Angestellte/-r
    * Finanzverantwortliche/-r
  * Gremium [layer_and_below_read -> layer_read]
    * Leitung 
    * Mitglied
    * Aktive/-r Kursleiter/-in

**Comment by nchiapol** [comment]
Mir ist eben noch eine Frage aufgefallen: Was genau enthält admin? Gewährt layer_full + admin Zugriff auf die unterliegenden Ebenen?

**Comment by RolandStuder** [comment]
@nchiapol  Nein, :admin gibt folgende Berechtigungen:
- Nächster Release: Personen ohne zugeordnete Rolle sehen
- Nächster Release: Personen definitiv löschen
- Etikettenformate / Emailtexte anpassen

Es benötigt eine layer_and_below... Berechtigung für darunterliegende Ebenen.

**Comment by nchiapol** [comment]
@RolandStuder Perfekt, das ist dann bestens so.

**Comment by RolandStuder** [comment]
@nchiapol
- Betrifft dies Dachverband und Mitgliederorganisationen?
- Euch ist klar, dass dies bedeutet, dass Personen der Geschäftsstelle, z. B. Coaches der Ortsgruppen damit nicht mehr sehen können?

**Comment by nchiapol** [comment]
@RolandStuder 
  * Das Betrifft nur den Dachverband. Bei den Mitgliederorganisationen sollen :layer_and_below_full bleiben.
  * Die Kommunikation zu den Ortsgruppen läuft über die Mitgliederorganisationen. Es reicht, wenn die Geschäftsstelle des Dachverbands die :contact_data rollen sieht.

**Comment by RolandStuder** [comment]
adressiert in https://github.com/hitobito/hitobito/issues/270
