### ISSUE TITLE
[BUG] Konto-Sperrung

### ISSUE THREAD

**Issue by maede97** [hitobito/hitobito_cevi#62]
Für den Cevi ist die Kontosperrung ja aktiv. @carlobeltrame hat uns per Mail mitgeteilt, dass nach 20 falschen Versuchen das Konto für 1h gesperrt ist.
Ich habe dies auf der Integration getestet und folgende 3 Bugs gefunden:
- Nach 20 Versuchen (bei mir waren es glaubs nur 19?), kommt diese Meldung oben: `Dein Account ist für 10 Minuten gesperrt.` Entweder stimmt die Angabe von Carlo nicht oder der Text ist falsch.
- Das Email mit dem Entsperr-Link ist nur englisch und mit Hello <Email_Adresse> adressiert. Diest wirkt sehr verdächtig für allfällige Nutzer der DB. Alle anderen Emails der CeviDB sind ja richtig "adressiert" und auch auf Deutsch.
- Nach einem Klick auf den Link im Email kommt folgende Meldung: `Dein Account wurde entsperrt. Du bist jetzt angemeldet.` Dies ist auch falsch, denn der Benutzer ist nicht angemeldet.

**Comment by olibrian** [comment]
Ticket wurde durch #1014 gelöst. Kann ab morgen auf der Integration getestet werden.

**Comment by maede97** [comment]
Habe dies eben getestet:
- Erfolgreiche Sperrung nach 5 Versuchen.
- Mail ist auf Deutsch (evtl. könnte jedoch nach dem Link noch ein "Footer" dazukommen? So etwas wie "wurde von der CeviDB gesendet (oder so))
- https://github.com/hitobito/hitobito/commit/9adef54988a530a201afb24763649a29fd5055da in diesem Commit wurde die Zeit auf `config.unlock_in = 1.hour` gesetzt. Angezeigt wird aber: `Dein Account ist für 10 Minuten gesperrt.` Nach 10 Minuten ist der Account aber noch gesperrt, also ist einfach noch der Text falsch.
- [ ] Text anpassen auf `Dein Account ist für 1 Stunde gesperrt.`

**Comment by TheWalkingLeek** [comment]
Hallo @maede97 
Merci fürs testen und melden!
Habe das soeben angepasst und gepushed (https://github.com/hitobito/hitobito/commit/0d0e8f16dc29f62bd649ae581782c754059434f2 & https://github.com/hitobito/hitobito_cevi/commit/d92be677a342773ab7061170e92806927ffe078a)
Das Ganze ist ab morgen auch wieder auf der Integration live

**Comment by maede97** [comment]
Habe dies soeben getestet. Sieht gut aus!
Danke vielmals!
Nur noch etwas kleines: https://github.com/hitobito/hitobito_cevi/blob/master/config/locales/views.cevi.de.yml#L84
Evtl. noch ein Punkt am Schluss vom Satz, danach könnt ihr von mir aus dieses Issue schliessen. :-)

**Comment by TheWalkingLeek** [comment]
Punkt ist eingefügt: https://github.com/hitobito/hitobito_cevi/commit/25516ed7e3ee51be07f14bc786767193c06a69f8 :)
