### ISSUE TITLE
Feature: Leiter können sich nur als Teilnehmer für einen Kurs anmelden

### ISSUE THREAD

**Issue by noahliechti** [hitobito/hitobito_cevi#67]
**IST**
Momentan können sich Leitende nicht für einen Kurs anmelden via DB, ohne dass sie automatisch als TNs erfasst werden. 
**Soll/Wunsch**
Leitende sollen die Möglichkeit haben sich mit anderen Rollen anzumelden.

**Comment by nchiapol** [comment]
duplicate https://github.com/hitobito/hitobito/issues/1276
