### ISSUE TITLE
Feature: Teilnehmende könne sich aus dem Kurs abmelden, Leitende aber nicht

### ISSUE THREAD

**Issue by noahliechti** [hitobito/hitobito_cevi#68]
**Ist**
Teilnehmende, die sich für einen Kurs angemeldet haben, können sich wieder "abmelden". Bei Leitenden ist dies nicht möglich, resp. müsste die Leitenden, die sich abmelden wollen, manuell vom Seki aus dem Kurs gelöscht werden.
**Soll**
Sowohl Teilnehmende als auch Leitende sollen sich aus einem Kurs selbstständig abmelden können.

**Comment by nchiapol** [comment]
Lösung via Wunsch: Kursleiter haben gleiche Rechte wie GS auf ihrem Kurs
