### ISSUE TITLE
Bug: QR Code Generierung funktioniert in der Testumgebung aber in der Live-Umgebung nicht

### ISSUE THREAD

**Issue by noahliechti** [hitobito/hitobito_cevi#69]
**Ist** 
Mit dem [QR-Validator ](https://www.swiss-qr-invoice.org/validator/) wird ersichtlich, dass der QR-Code in der Testumgebung richtig generiert wird, jener in der Live-Umgebung aber nicht. Die Funktion ist also zurzeit unbrauchbar.

Ergebnis QR-Validator Testumgebung:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/38284563/132245864-0c95a353-0010-46d7-92c4-4617fb352f50.png">

Ergebnis QR-Validator Liveumgebung
![image](https://user-images.githubusercontent.com/38284563/132245942-6b9fa360-1d5b-4c28-bb0c-962a88553187.png)

[QR-Rechnung_Testumgebung_2021-08-27.pdf](https://github.com/hitobito/hitobito_cevi/files/7117193/QR-Rechnung_Testumgebung_2021-08-27.pdf)

[QR-Rechnung_Live-Umgebung_2021-08-27.pdf](https://github.com/hitobito/hitobito_cevi/files/7117196/QR-Rechnung_Live-Umgebung_2021-08-27.pdf)

**Soll**
Das erstellen einer Rechnung mit QR-Code muss in der Live-Umgebung funktionieren. Ab September 2022 wird es nur noch QR-Rechnungen geben. Da es Sinn macht Finanz-Sachen per Anfang Jahr einzuführen und eine Übergangsfrist wünschenswert wäre ist es enorm wichtig, dass dies Funktion bis Ende Jahr funktioniert.

**Comment by nchiapol** [comment]
Liegt wohl an der alten Version auf dem produktiv System. Sollte mit dem nächsten Release gelöst sein.
