### ISSUE TITLE
Indikation von "zu jung" /  "zu alt" bei TN Listen (12h)

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_cevi#7]
Von der Cevi:

Die TN Listen sollten eine Markierung für zu Jung/zu Alt enthalten. Die zu jung Markierung bei
den Anmeldungen ist im Moment nicht für alle relevanten Personen
sichtbar. (Zu alt ist neue, da müssten wir die Definition noch klären.)
 
Anforderungen noch sehr unklar. Wir möchten aber ein Schätzung wie komplex das im Vergleich zu den anderen Issues ist.

**Comment by nchiapol** [comment]
Vielen Dank für die Schätzung, wir werden das vorerst nicht weiter verfolgen.

**Comment by nchiapol** [comment]
kann geschlossen werden
