### ISSUE TITLE
Feature: Rechnungs-Nummer kann selber gewählt werden

### ISSUE THREAD

**Issue by noahliechti** [hitobito/hitobito_cevi#71]
**Ist** 
Die Rechnungs-Nummer ist aktuell fix vorgegeben. 

**Soll/Wunsch**
Könnte diese manuell eingestellt werden (z.B. Jahreszahl und dann fortlaufende Nr.), so wäre es intuitiver.

**Comment by nchiapol** [comment]
braucht noch diskussion; in internen Tracker verschoben,
