### ISSUE TITLE
Bug: Konto-Stelle wird in der Rechnung nicht angezeigt

### ISSUE THREAD

**Issue by noahliechti** [hitobito/hitobito_cevi#73]
**Ist**
Konto-Stelle wird z.T. noch nicht angezeigt (Problem kann momentan nur umgangen werden, in dem man eine neue Rechnung erstellt, nur den Titel eingibt, den Entwurf speichert und dann erneut bearbeitet und speichert.)
**Soll**
Die Konto-Stelle soll ohne grosse Umwege auf der Rechnung angezeigt werden.

**Comment by CalvinYMCA** [comment]
Zitat Seki WS:
Wenn mer e Rechnig neu erstellt und bide Kostenstelle e Zahl itreit, denn d Rechnig abspeicheret und wieder aluegt, isch d Kostenstelle wieder leer.

**Comment by chrusu** [comment]
@noahliechti kannst du hier eine genauere problembeschreibung machen? wir konnten dies auf der Integration nicht nachstellen

**Comment by maede97** [comment]
evtl. zusammenhängend mit #77 ?

**Comment by nchiapol** [comment]
Ich kann das auf der Integration nicht nachvollziehen. Kann das bitte jemand kontrollieren und allenfalls Screenshots ergänzen, sollte das Problem weiter bestehen?

**Comment by nchiapol** [comment]
keine news, betrachten wir als gefixt.
