### ISSUE TITLE
Anmeldungen sind automatisch zugeteilt 

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#74]
Ich kann mich nicht errinnern, dass wir hier eine Änderung gewünscht haben. 

Für den Cevi Alpin ist das unpraktisch - und im Rahmen von https://github.com/cevi/hitobito_cevi/issues/101 möchten wir das sowieso anders. 

https://cevi.puzzle.ch/groups/5/events/1106
-> Anmelden, die Anmeldung landet unter Zugeteilte Teilnehmende und nicht unter "Anmeldungen" sondern direkt unter "Zugeteilte Teilnehmende"

**Comment by chrusu** [comment]
@nchiapol kannst du das noch etwas genauer ausführen?

**Comment by carlobeltrame** [comment]
Merci für die Meldung. Die Änderung ist im Rahmen von https://github.com/hitobito/hitobito_sjas/issues/27 entstanden, wo die SJAS gewünscht hatten, die Warteliste / Anmeldungs-Spalte auch für Lager und Anlässe zu verwenden, aber dabei Anmeldungen automatisch zuzuteilen solange es noch Platz im Kurs hat.
Wir haben da eigentlich eine Unterscheidung eingebaut, die verhindern sollte dass das bei den Jugendverbänden Auswirkungen hat: Für Anlasstypen bei welchen Priorisierung (1. Wahl, 2. Wahl, 3. Wahl) aktivierbar ist (in der Praxis sind das nur Kurse), ist diese direkte Anmeldung deaktiviert. Das macht einigermassen Sinn, weil in priorisierbaren Kursen die Anmeldung in zwei Schritten nötig ist (wenn die TN mehrere Prioritäten angeben können muss auch jemand die Prioritäten anschauen und die TN entsprechend zuteilen).
Bei euch wurde aber diese Priorisierung auf Kursen in https://github.com/hitobito/hitobito_cevi/issues/42 generell komplett deaktiviert. Daher greift die Unterscheidung bei euch nicht, und ihr beobachtet die direkten Anmeldungen bei euren Kursen. Dasselbe Problem tritt also bei den anderen Jugendverbänden momentan nicht auf.

Die schnellste Lösung wäre es, die Priorisierung auf Kursen auch bei euch zu ermöglichen. Das heisst noch nicht, dass alle Kurse die Priorisierung direkt aktiviert haben würden, sondern sie bekämen eine Checkbox, mit dem sie pro Kurs Priorisierung aktivieren oder deaktivieren könnten (Default: deaktiviert).
![Screenshot from 2021-11-23 18-07-36](https://user-images.githubusercontent.com/7566995/143071065-d406cd0b-ee7c-44d4-be34-ae1388a97d8c.png)

Ihr könntet dann den Kursleitenden noch raten, diese Checkbox nicht zu benutzen, oder sie gar nicht darauf hinweisen, dann bliebe für euch alles beim Alten, und das Problem wäre gefixt. Falls dann ein Kurs die Checkbox dennoch aktiviert, würde den TN die Auswahl der zweiten und dritten Priorität angeboten:
![Screenshot from 2021-11-23 18-10-59](https://user-images.githubusercontent.com/7566995/143071513-8bb722f5-b4bf-483c-9eda-9cda266711e7.png)

Falls euch die Priorisierung dann schlussendlich gar nicht passt hätten wir dafür in der Zwischenzeit etwas mehr Zeit, das Ganze auch für euren Fall korrekt umzubauen, mit der zweiteiligen Anmeldung aber ohne Priorisierung.

Falls ihr das aber gar nicht verantworten wollt mit der Möglichkeit der Priorisierung, könnte ich diesen Umbau auch direkt vornehmen, das dauert aber natürlich etwas länger. Je nach dem wie dringend ihr wieder das alte Verhalten braucht.

**Comment by nchiapol** [comment]
Vielen Dank für das ab- und erklären. Mit der einfachen Lösung "Priorisierung auf Kursen ermöglichen" sollten wir im Moment gut leben können. Eine allgemeine Überprüfung/Optimimerung unseres Anmeldeprozesses steht sowieso ziemlich weit oben auf unserer Pendenzenliste. Entsprechend macht es Sinn, hier im Moment möglichst wenig Energie zu investieren und das dann gemeinsam mit unseren anderen Anliegen sauber zu lösen.
