### ISSUE TITLE
Auto-Loggout ist störend

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#75]
``Unsere Geschäftsstelle hat sich heute Beschwert:

> Seit dem letzten Cevi.DB Update wird man nach ca. 5-10min inaktiver Zeit automatisch von der Cevi.DB abgemeldet und man muss sich wieder neu anmelden. Dies passiert auch, wenn man das Häkchen „angemeldet bleiben“ aktiviert.
Gibt es einen Grund für diese Änderung? Wenn man täglich mit der Cevi.DB arbeitet, ist es natürlich praktisch, wenn man die Seite immer offen haben kann und man sich nicht 10mal pro Tag neu anmelden muss.

**Comment by maede97** [comment]
Hängt das mit https://github.com/hitobito/hitobito/issues/1018 zusammen? Wurde da bereits etwas umgesetzt?

**Comment by nchiapol** [comment]
scheint nicht mehr relevant
