### ISSUE TITLE
Konto und Kostenstelle wird bei Sammelrechnungen und Rechnung an Event nicht gespeichert.

### ISSUE THREAD

**Issue by MrTinnysis** [hitobito/hitobito_cevi#77]
Konto und Kostenstelle wird bei Sammelrechnungen und Rechnung an Event nicht gespeichert.

Schritte:

1. Rechnung für eine Gruppe (Sammelrechnung) erstellen
2. Rechnungsposition mit Konto und Kostenstelle hinzufügen
3. Rechnung speichern

oder:

1. Rechnung für einen Anlass/Kurs mit mehr als einer Person erstellen
2. Rechnungsposition mit Konto und Kostenstelle hinzufügen
3. Rechnung speichern

In beiden Fällen sind beim erneuten öffnen der Rechnung die Felder Konto & Kostenstelle leer.

**Comment by carlobeltrame** [comment]
Im invoice_lists_controller fehlen in den permitted_attrs die Einträge `:cost_center` und `:account`. Diese müssen [hier](https://github.com/hitobito/hitobito/blob/master/app/controllers/invoice_lists_controller.rb#L27) ergänzt werden, dann sollte das funktionieren.
