### ISSUE TITLE
Kurs-Teilnehmer können nicht zu Kurs-Mitarbeitern gemacht werden (und umgekehrt) (8h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#8]
Bei Anlässen kann die Rolle einer Person zwischen Teilnehmer und Leiter umgestellt werden. Bei Kursen ist das nicht möglich. Das ist störend, da sich Kurs-Mitarbeiter so nicht via DB anmelden können.
(Wir sehen das als Bug.)

Bitte schätzen, was der Aufwand wäre die Rolle zwischen Teilnehmer und Letier umstellen zu können.

**Comment by RolandStuder** [comment]
Bei Teilnehmer gibt es mehrere Stati (abgemeldet / abgelehnt), die es bei Kursmitarbeitern nicht gibt, deshalb war eine 1 zu 1 Rollenumteilung bisher nicht drin. Dies können wir deshalb nicht einfach  als Bug anschauen.

**Comment by nchiapol** [comment]
OK, ich sehe den Unterschied und verstehe, dass ihr das nicht als Bug seht. Unschön ist das trotzdem. (Aber wohl nicht so wichtig, dass wir da im Moment viel Geld investieren möchten.)

**Comment by codez** [comment]
Müsste abgeklärt werden, wo das überall einfliessen würde (Zuteilung, Empfehlungen, ...)
Schätzung: bis 1PT

**Comment by nchiapol** [comment]
Der eigentliche Use-Case hier ist wohl, dass Personen via CeviDB ihr Interesse an der Mitarbeit im Leiterteam melden können. Entsprechend wäre auch eine separate "Leiteranmeldung" eine mögliche Lösung.

**Comment by chrusu** [comment]
- Interesse an der Mitarbeit im Leiterteam melden
- Nur Interese melden / anzeigen
- Neue Art von Rollen im Event, Möglichkeit zum Konvertieren zum Kursleiter

**Comment by chrusu** [comment]
@nchiapol : Im Rahmen der Umsetzung sind noch 2 Fragen aufgetaucht:

1) ist es gewünscht/sinnvoll, dass der neu zum Leiter mutierte Teilnehmer weiterhin zusätzlich als Teilnehmer geführt werden kann/soll?

2) sollen wir dem "mutierten" Teilnehmer automatisch die Gruppe Leitung zuweisen (kann nachträglich natürlich angepasst werden), oder soll manuell eine Rolle ausgewählt werden (Hauptleitung, Leitung, Küche, Kassier, etc.)?

**Comment by kronn** [comment]
Ich habe es erstmal so implementiert, das man als interessierter Teilnehmer zusätzlich eine Leitungsrolle bekommen kann. Welche das ist, muss direkt aus einem Dropdown ausgewählt werden. Die Rolle Teilnehmer bleibt erstmal unverändert. Wenn man die Teilnehmerrolle entfernen können möchte, kann man dies noch anpassen. 

Vorerst mache ich dieses Ticket hier zu, bei Änderungswünsche kann man es wieder eröffnen oder ein neues Ticket erstellen.

**Comment by nchiapol** [comment]
Sorry für die fehlende Reaktion. Kann ich das schon auf der Integration testen? 

Grundsätzlich gehe ich nicht davon aus, dass jemand eine TN + eine Leiter Rolle braucht. Wenn ich aber einen TN einfach zu einem Leiter machen kann und die den Rolle in einem separaten Schritt noch löschen kann (wie bei jedem TN) ist das wohl die flexibelste Lösung und passt für uns. (Die Leiter-Rolle kann ich ja ebenfalls in einem zweiten Schritt noch anpassen, auch das passt für uns.)

**Comment by kronn** [comment]
Gestern noch nicht, heute ist das Feature auf der Integration verfügbar. Grundsätzlich wird (mittlerweile) immer nachts der aktuelle Code dort verfügbar gemacht. 

Aktuell ist es noch so, dass die Teilnehmerrolle nicht separat gelöscht werden kann. Aufgrund dieses Feedbacks passe ich dies noch so an, dass auch die Teilnehmerrolle entfernt werden kann, wenn mehrere Rollen vorhanden sind. Die konkrete Leiterrolle kann in der aktuellen Lösung ausgewählt werden, aber auch wie bisher nachträglich angepasst werden.

**Comment by kronn** [comment]
@nchiapol morgen ist die entsprechende Anpassung auf der Integration sichtbar. Wenn jemand mehrere Rollen hat, kann auch die Teilnehmerrolle gelöscht werden. Dies passiert, wenn ein Teilnehmer Interesse am Leiterteam gemeldet hat und daraufhin eine weitere (Leitungs-)Rolle gekommen hat. Damit ist es optional, ob ein Teilnehmer komplett in die Leitung wechselt oder beide Rollen hat.

**Comment by nchiapol** [comment]
Vielen Dank für die Rückmeldungen, die Flexibilität mit den beiden Rollen finde ich super. Davor scheint mir der Prozess aber noch nicht ganz überzeugend. Dinge die mir aufgefallen sind:
  * Da der Knopf "Mitarbeit im Leiterteam" nicht im eigentlichen Anmeldeprozess enthalten ist, wird er wohl leicht übersehen.
  * Da der Knopf "Mitarbeit im Leiterteam" keine zusätzliche Info erlaubt, muss die gewünschte Rolle auf anderem Weg kommuniziert werden (entweder in den Bemerkungen bei der Anmeldung oder auf per Mail/Telefon)
  * Für den Kursadmin ist es nicht rasch ersichtlich, wer als Leiter mithelfen möchte. Die einzige  Hinweis ist der Button auf den Teilnehmerdetails 
  * Der Button auf den Teilnehmerdetails heisst "Person hinzufügen", funktioniert aber eigentlich als "Rolle hinzufügen" und sollte deshalb so bezeichnet werden.
  * Der Dialog danach erlaubt es tatsächlich eine andere Person hinzuzufügen. Logischer wäre wohl der "Rolle bearbeiten" Dialog. (Wobei man das auch als Feature sehen kann.)
  * Der Button "Person hinzufügen" wird nur angezeigt, wenn jemand "Mitarbeit im Leiterteam" angeklickt hat. Als Kursadmin kann ich deshalb nicht selbständig jemanden zum Leiter machen, auch wenn ich das z.B. eben per Telefon besprochen hatte.

Ich denke, der "Mitarbeit im Leiterteam" war eine interessante Idee, macht das Ganze aber unnötig kompliziert. Mein Vorschlag deshalb:
  * "Mitarbeit im Leiterteam"-Button wieder entfernen
  * Den Button "Rolle hinzufügen" bei allen TN anzeigen 
    * das erlaubt es dem Admin TN selbständig zu Leitern zu machen
    * ob der Button den "Person hinzufügen"- oder "Rolle bearbeiten"-Dialog öffnet ist beides OK.
  * Das Interesse für die Mitarbeit im Leiterteam kann dann via "Anmeldeangaben" abgefragt werden.
    * Die Frage kann mit den für diesen Kurs passenden Auswahl-Optionen konfiguriert werden.
    * Die Frage ist fixer Bestandteil des Anmeldeprozesses und wird nicht übersehen. 
    * Die Antwort kann auf der TN-Liste angezeigt werden

Alternativ könnte die Info zum gemeldeten Interesse "Mitarbeit im Leiterteam" auch auf den Tabs "Teilnehmende" und "Anmeldungen" angezeigt werden. Der Button auf den Teilnehmerdetails sollte aber auf jeden Fall bei allen Anmeldungen anzeigt und zu "Rolle hinzufügen" umbenannt werden.

**Comment by kronn** [comment]
Ich habe es entsprechend angepasst, es sollte mittlerweile auf der Integration sichtbar sein. Die Frage ist jetzt als globale Frage hinterlegt und wird jedem neuen Kurs zugeordnet. Wenn das bei einem Kurs nicht oder mit einer anderen Formulierung gewünscht ist, kann es normal angepasst werden. Die globale Frage ändert sich nicht. 

In der TN-Liste kann man die Antwort(en) anzeigen lassen. Dies ist mit dem Erweiterungsmenü möglich, in dem auch die Anmeldeangaben verfügbar sind.

Ich schließe dieses Ticket erstmal (wieder :wink:), bei Änderungswünschen kann man es natürlich wieder eröffnen.

**Comment by nchiapol** [comment]
Sorry für die lange Stille an unserem Treffen letzte Woche haben wir noch zwei kleine Anpassungswünsche identifiziert:

#### Formulierung Frage:
Wir möchten die default-Auswahl aufs Minimum reduzieren. Das reicht in den allermeisten Fällen und veraltet sicher auch weniger rasch.
```
Ich habe Interesse an der Mitarbeit im Leitungsteam als: 
Gruppenleiter/-in, Küche, andere Funktion
```
Könnt ihr das noch entsprechend anpassen?

#### Teilnehmer-Rolle
Unseren Ausbildungsverantwortlichen haben noch gewünscht, dass wir ihnen ein paar Klicks sparen. Könnt ihr den "Rolle hinzufügen"-Dialog um eine Checkbox "Teilnehmer/-in Rolle entfernern" ergänzen (default selected), so dass die Rolle gleich mitgelöscht werden kann?

![image](https://user-images.githubusercontent.com/1123483/110074397-74471200-7d81-11eb-8c87-1323db72ab43.png)

(Bitte meldet euch, falls das eine grössere Sache ist und nicht gemeinsam it Tickets #53 und #54 ins Budget passt.)

**Comment by chrusu** [comment]
TODO um dieses Issue abzuschliessen:

Formulierung Frage:
Wir möchten die default-Auswahl aufs Minimum reduzieren. Das reicht in den allermeisten Fällen und veraltet sicher auch weniger rasch.

Ich habe Interesse an der Mitarbeit im Leitungsteam als: 
Gruppenleiter/-in, Küche, andere Funktion

Für die Löschung der Teilnehmer-Info wurde ein neues Issue erstellt #1220
