### ISSUE TITLE
Kurs-Leiter haben zu viele Rechte (2h)

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito_cevi#9]
Kurs-Leiter sollten die gleichen Rechte an der TN-Liste haben wie die Küche, nicht wie der Hauptleiter. (Wir sehen das als Bug)

Konkret geht es um die Rolle AssistantLeader (https://github.com/hitobito/hitobito/blob/92db15a8e375d93f9634c3138335169e8dd6b76a/app/models/event/role/assistant_leader.rb) und nicht um die Hauptleitung. Im Core hat diese volle Berechtigung. Müsste im Wagon überschrieben werden.

Gilt für Events wie Kurse

Machen wir im Wagon.

**Comment by RolandStuder** [comment]
Wenn ich mich nicht täusche sind die Rechte auf TN Liste bei allen Organisationen bisher gleich. Wir müssen schauen, was das für Konsequenzen hätte und ob wir das einfach bei nur euch anpassen könnten.

**Comment by nchiapol** [comment]
Falls das bei den anderen Organisationen gewünscht ist, dass normale Leiter erweiterte Rechte haben, sind wir an den UseCases interessiert.

**Comment by codez** [comment]
Schätzung: 0.25PT

**Comment by RolandStuder** [comment]
abgedeckt durch https://github.com/hitobito/hitobito/issues/276
