### ISSUE TITLE
EVENTS: Nacharbeiten zu: Konfiguration pro Kurs, ob direkt angemeldet, oder manuell zugewiesen (Warteliste)

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_cevi#95]
Folgeissue zu #79

Die Cevi hat nach dem Testen des Features noch einige Anmerkungen welche in diesem Issue zusammengefasst werden. Vorerst werden nicht alle Wünsche umgesetzt.

## Umzusetzende Anliegen

  - Die Checkbox "Verwendet Warteliste" soll zu "Verwendet Voranmeldung" umbenannt werden
  - Für die Cevi soll es nur noch eine Checkbox geben, welche ihre beiden Fälle unterscheidet (vgl. https://github.com/hitobito/hitobito_cevi/issues/79#issuecomment-1314376779): "Verwendet Voranmeldung [ ] Teilnehmende können sich selbst nur voranmelden und müssen dann manuell zugewiesen werden."
    - `true`: Ablauf (b), entspricht aktuell 
![image](https://user-images.githubusercontent.com/1123483/204388157-fbdb2d2d-b5b8-49d2-b5fa-4935063f5505.png)
    - `false`: Ablauf (a), entspricht aktuell  ![image](https://user-images.githubusercontent.com/1123483/204387843-3cbcaefc-9704-44fa-b740-35da708bc53f.png)
    
    Für die Cevi ist also "Verwendet Voranmeldung" immer true. @nchiapol: Können wir dieses Feld einfach immer true machen und für euch ausblenden? Und ihr hättet dann nur noch die auswahlmöglichkeit "Warteliste" zur Auswahl? Oder wie stellt ihr euch das vor?

  - In der Info-Box im Screenshot im letzten Kommentar fehlt ein "die":  "... Voranmeldung für DIE Teilnahme von ..."

 - Das Feld "Status" ist verwirrend, wenn die Anmeldung noch nicht definitiv ist.
Es müsste heissen:
"Vorangemeldet" und danach "Zugeteilt" (anstelle von "Angemeldet" und "Zugeteilt")
![image](https://user-images.githubusercontent.com/14098502/204355851-5a46d2ca-1c7c-429f-8a06-224443d34a8b.png)

## Nicht umgesetzte Anliegen

  - Bei Ablauf (a) wird aktuell ebenfalls die "Voranmeldungs-Info-Box" gemäss Screenshot angezeigt und das Voranmeldungs-Email ausgelöst. (vgl. https://github.com/hitobito/hitobito_cevi/issues/79#issuecomment-1314853090) Bitte in diesem Fall beides unterdrücken.

- Solange eine Anmeldung unter "Anmeldungen" noch auf der rechten Seite (also noch nicht zugeteilt) ist, wird diese Anmeldung auf der Profilseite auch separat aufgeführt: 
![image](https://user-images.githubusercontent.com/1123483/204733982-443b12c9-546f-4962-be77-ed66ff9a462c.png)
Klicke ich auf diesen Link, komme ich auf .../events/.../participations/... (https://cevi.puzzle.ch/groups/6/events/1171/participations/127823) auf allen anderen Wegen erreicht man nur .../events/... (https://cevi.puzzle.ch/groups/6/events/1172).
Das ist grundsätzlich ok, allerdings wird auf dieser Seite der Hinweis "Du bist für diesen Anlass vorangemeldet. Die Anmeldung ist noch nicht definitiv und muss von der Kursadministration bestätigt werden." nicht angezeigt. Damit alles konsistent ist, wäre es super, wenn das dort auch noch angezeigt werden könnte (oder der Link ebenfalls direkt auf .../events/... verweisen würde.)

- Bei der Konfiguration ohne Voranmeldung besteht keine Möglichkeit, manuell ein*e Teilnehmer*in hinzuzufügen. Bei Kursen ist dies nur via Tab «Anmeldungen» möglich, bei Anlässen via Tab «Teilnehmende». 
Aus meiner Sicht wäre es wohl die beste Lösung den Teil der Anpassungen, der bei `Verwendet Voranmeldung = false` aktiv ist und bei Kursen eine "Anlass-Anmeldung" erzeugt (und nicht eine automatisch zugewiesene Kursanmeldung) ganz zu reverten.

## Todo
- [ ] `de.activerecord.attributes.event/course.supports_applications` im Core models.de.yml auf "Verwendet Voranmeldung" ändern
- [ ] ... weitere Anforderungen tbd

**Comment by nchiapol** [comment]
@ThomasEllenberger:
> Können wir dieses Feld einfach immer true machen und für euch ausblenden? Und ihr hättet dann nur noch die auswahlmöglichkeit "Warteliste" zur Auswahl? Oder wie stellt ihr euch das vor?

Technisch schon, aber: der angezeigte Text sollte Warteliste nicht erwähnen. Stattdessen möchten wir, dass der Text "Verwendet Voranmeldung [ ] Teilnehmende können sich selbst nur voranmelden und müssen dann manuell zugewiesen werden." angezeigt wird. (Der aktuelle Text ist bei unseren Abläufen verwirrend)

> Bei der Konfiguration ohne Voranmeldung besteht keine Möglichkeit, manuell eine Teilnehmerin hinzuzufügen. [...]

Wichtig: Das ist eine Situation, die es bei uns nicht vorkommen kann, da das Feld immer true ist. Da die Konfiguration aber zu diversen Bugs führt, ist es wohl im Interesse aller, wenn das ganz verhindert wird. Falls das viel Aufwand ist, möchten wir dafür aber natürlich kein Geld ausgeben - wir haben diverse dringendere Anliegen ;-)
